# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
DEPLOYMENT_ENV: dev

springdoc:
  swagger-ui:
    path: /swagger
server:
  port: 8086
  error:
    include-message: always
