# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
DEPLOYMENT_ENV: dev

springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: 8084
  error:
    include-message: always
  forward-headers-strategy: framework
