# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  rabbitmq:
    port: 5672
    host:
  cache:
    redis:
      time-to-live: 5S #86400S # === 1 day
  thymeleaf.cache: false
  datasource:
    username: user
    url: jdbc:postgresql://127.0.0.1:5432/team-service
    driverClassName: org.postgresql.Driver
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
      enable-lazy-load-no-trans: true
    show-sql: 'true'
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
  main:
    banner-mode:
server:
  port: 9000
  error:
    include-message: always

DEPLOYMENT_ENV: dev

