# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  cache:
    redis:
      time-to-live: 1S # 86400S # === 1 day
  thymeleaf.cache: false
  datasource:
    #username: neekh
    username: compose-postgres

    url: jdbc:postgresql://localhost:5432/team-service
    driverClassName: org.postgresql.Driver
    #password: kbe
    password: compose-postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
  main:
    banner-mode:
server:
  port: 8081
  error:
    include-message: always

DEPLOYMENT_ENV: dev

springdoc:
  swagger-ui:
    path: /swagger
