FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD product-service.jar /opt/product-service/
EXPOSE 8080
WORKDIR /opt/product-service/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "product-service.jar"]
